from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional

class QueryRequest(BaseModel):
    query: str = Field(..., description="The query text to search for.")

class SourceDoc(BaseModel):
    passage_id: str
    passage: str
    score: float
    metadata: Dict[str, Any] = Field(default_factory=dict)

class LatencyBreakdown(BaseModel):
    stt_ms: Optional[float] = Field(None, description="Speech-to-Text latency in ms.")
    retrieval_ms: float = Field(..., description="Vector retrieval latency in ms.")
    llm_ms: float = Field(..., description="Language model generation latency in ms.")
    total_ms: float = Field(..., description="Total pipeline latency in ms.")

class QueryResponse(BaseModel):
    request_id: str = Field(..., description="Unique request identifier.")
    query: str = Field(..., description="The query string (either input text or STT transcription).")
    answer: str = Field(..., description="The final grounded answer generated by the LLM or standard guardrail refusal.")
    sources: List[SourceDoc] = Field(default_factory=list, description="List of source passages retrieved from vector DB.")
    latency: LatencyBreakdown = Field(..., description="Breakdown of stage-wise processing latency in ms.")
    guardrail_refusal: bool = Field(False, description="True if any L1/L2/L3 guardrail triggered a refusal response.")

class WarmupResponse(BaseModel):
    status: str
    message: str

class HealthResponse(BaseModel):
    status: str
    qdrant_connected: bool
    version: str
